### ISSUE TITLE
What does this library provide over plain javascript?

### ISSUE THREAD

**Issue by Jon-Biz** [hiowenluke/kdo#1]
I've looked through the documents and examples and I'm still unclear what this library provides over plain javascript. The amount of boilerplate seems mostly unchanged, but plain js is, inherently, easier to parse. Take the base example:

```
const foo = async () => {

// do something for task 1
// ...

// do something for task 2
// ...

// do something for task 3
// ...

// do something for task 4
// ...

}

```

What does kdo provide, over this solution:

```
const task1 = async (...args) => {
  ...
  return [ ...results ]
}

const task2 = async (...args) => {
  ...
  return [ ...results ]
}

const task3 = async (...args) => {
  ...
  return [ ...results ]
}

const task4 = async (...args) => {
  ...
  return [ ...results ]
}

const foo = async (...args) => {
  const result1 = await task1(...args)
  const result2 = await task2(...result1)
  const result3 = await task3(...result2)
  const result4 = await task4(...result3)

  return result4
}
```

The separate functions have the added advantage of being modularizable without cruft spread operations, unlike the flow object in the kdo examples.

Thanks!

**Comment by hiowenluke** [comment]
Thank you for your question. Let's clear it.
There are many benefits to using kdo + flow (object or files) instead of plain functions:

**1. Easily pass data**

Consider the below code:

```js
// Good

const flow = {
    async f1({a1, a2, a3}) {
    	a1 === 1; // true
		
        // do something
        const x = a1 + 5; // 6
        a1 = 0;

        // save the x to arguments
        // kdo will pass it to next functions, cool!
        this.save({a1, x});
    },

    async f2({a1, a2, x}) {
        a1 === 0; // true, the value is changed in f1
        x === 6; // true, the value is passed from f1
        a2 = x + 1;
        this.save({a2});
    },

    async f3({a2, a3, x}) {
        a2 === 7;
        x === 6;
    }
};

const main = async () => {
    
    // initialize variables which will be passed to flow
    const args = {a1: 1, a2: 2, a3: 3};
    
    await kdo.do(flow, args);
};
```
Each of the above functions is very concise and the logic is clear and easy to understand.

If we use plain functions, like below, the code in main function is complicated, multiple parameters and return values make the code look uncomfortable and not easy to read.

And, the main problem is that the main function performs data disassembly and transfer. When we change the input and output parameters of the sub-function, we have to modify the related code of the main function at the same time, which means that the sub-function is not completely encapsulated.


```js
// Not good

const f1 = async ({a1, a2, a3}) => {
    a1 === 1; // true

    // do something
    const x = a1 + 5; // 6
    a1 = 0;

    return {a1, x};
};

const f2 = async ({a1, a2, x}) => {
    a1 === 0;
    x === 6;
    a2 = x + 1;

    return {a2};
};

const f3 = async ({a2, x}) => {
    a2 === 7;
    x === 6;
};

const main = async () => {
    let a1 = 1, a2 = 2, a3 = 3, x;

    // Multiple parameters and return values make the code
    // look uncomfortable and not easy to read
    ({a1, x} = await f1({a1, a2, a3}));
    ({a2, x} = await f2({a1, a2, x}));
     await f3({a2, x});
};

```


**2. Clear process control**

Consider the below code:

```js
// Good

let flag = 1;

const flow = {
    async f1() {
        // do something
    },

    async f2() {
        if (flag === 1) return true; // note this statement
        // do something
    },

    async f3() {
        // do something
    }
};

const main = async () => {
    await kdo.do(flow);
};
```

The condition flag ===1 is met in f2 , so the f3 will be ignored. We do not need to add redundant code in main function.

If we use plain functions, like below, the code that handles flag === 1 is spread across two places, f2 and main. When we change the condition of flag === 1, we need to modify these two places. If the code is long, or these functions spread across many files, then we may miss something.

And, the code in main function will not elegant (yes, writing elegant code is one of my goals).

```js
// Not good

const f1 = async () => {
    // do something
};

const f2 = async () => {
    if (flag === 1) return true;
    // do something
};

const f3 = async () => {
    // do something
};

const main = async () => {
    await f1();

    // the code that handles flag === 1 is spread across two places
    const result = await f2();
    if (!result) {
        await f3();
    }
};
```



**3. Flexible return value**

Sometimes, in order to make the code structure clear, we will classify the flow functions into multiple files in a multi-level directory. 

In the task flow, after a file is processed, if a non-undefined value is returned, kdo will terminate the subsequent processing and return it to the main function. 

We do not need to write additional complex code. Yes, if we use plain functions instead of kdo, there must be a lot of redundant code to handle the same logic.

```js
// Good

// require the sub-directory as flow object 
const flow = require('./09-flow');

const main = async () => {
	const args = {str: ''};

        // kdo returns the value 123 to main function.
        // this value was returned from ./09-flow/flow1/flow12/f122.js
	const result = await flow(args);
	result === 123; // true
};
```

The code in ./09-flow/flow1/flow12/f122.js:

![](https://raw.githubusercontent.com/hiowenluke/kdo/master/doc/img/qa-001.jpg)

**Comment by hiowenluke** [comment]
This answer has been merged into the readme. Thanks again.
